"""Chats tables added'

Revision ID: 2645b9b0ca7d
Revises: 58c58651f60a
Create Date: 2024-11-23 23:39:50.617702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2645b9b0ca7d'
down_revision: Union[str, None] = '58c58651f60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
