"""Messages table edited 2

Revision ID: 49b5e656e4d6
Revises: baae501d10dc
Create Date: 2024-11-24 14:50:39.066805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b5e656e4d6'
down_revision: Union[str, None] = 'baae501d10dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('message', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'message')
    # ### end Alembic commands ###
