"""Chats tables added'

Revision ID: 97a9011a4ecf
Revises: 2645b9b0ca7d
Create Date: 2024-11-23 23:41:41.878328

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '97a9011a4ecf'
down_revision: Union[str, None] = '2645b9b0ca7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_chat_messages_id'), 'chat_messages', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_chat_messages_sequence_number'), 'chat_messages', ['sequence_number'], unique=False, schema='public')
    op.create_table('chats',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_index(op.f('ix_public_chats_id'), 'chats', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_chats_id'), table_name='chats', schema='public')
    op.drop_table('chats', schema='public')
    op.drop_index(op.f('ix_public_chat_messages_sequence_number'), table_name='chat_messages', schema='public')
    op.drop_index(op.f('ix_public_chat_messages_id'), table_name='chat_messages', schema='public')
    op.drop_table('chat_messages', schema='public')
    # ### end Alembic commands ###
