"""Messages table edited

Revision ID: baae501d10dc
Revises: 97a9011a4ecf
Create Date: 2024-11-24 10:42:25.518150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baae501d10dc'
down_revision: Union[str, None] = '97a9011a4ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('action', sa.String(length=50), nullable=False))
    op.add_column('chat_messages', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('chat_messages', 'message')
    op.drop_column('chat_messages', 'sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('sender', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('chat_messages', 'username')
    op.drop_column('chat_messages', 'action')
    # ### end Alembic commands ###
